name: RanksItems
api: [4.0.0]
version: 0.1
main: Thaili\Main
author: Thaili
description: "ยง4Use a special item so that when using the click ofUse a special item so that when using the click of a command is executed"



commands:
  rankitem:
    description: "ยง3Help RankItem"
    permission: rank.item.give
  
permissions: 
  rank.item.give:
    default: op
    description: xd
